leftnav:
- identifier: e1b3461b-253c-5698-0604-5d88bce419dc
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 5cf73171-6f19-2353-353d-49dfd52fda14
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: acd70d52-ee88-6cbd-a959-96da74024551
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 2562bfe9-88c5-05a2-3857-915ae8e3af03
  name: Labs
  url: /pages/labs
  weight: 40
- identifier: a27e649b-9323-7184-f4ba-4b4fa758e942
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: f33ec800-3608-1163-c520-7d0dcdb069f1
  name: Study Materials
  url: /pages/study-materials
  weight: 60
- identifier: bf669100-260c-02d4-6bd1-c90a908d1f26
  name: Related Resources
  url: /pages/related-resources
  weight: 70
